spring:
  application:
    name: Ludoteque
  config:
    import: optional:file:./secrets.yml
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
